# Generated by Django 4.0.4 on 2022-06-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapatos', models.CharField(max_length=100)),
                ('camisetas', models.CharField(max_length=100)),
                ('calcas', models.CharField(max_length=100)),
                ('chapeus', models.CharField(max_length=100)),
                ('shorts', models.CharField(max_length=100)),
            ],
        ),
    ]
